services:
  - type: web
    name: binance-trading-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: API_KEY
        sync: false
      - key: API_SECRET
        sync: false
    autoDeploy: true
    plan: free 